### ISSUE TITLE
Allow to use pixi-installed binaries without custom shell

### ISSUE THREAD

**Issue by borchero** [prefix-dev/setup-pixi#103]
When "activating" a Pixi environment in my local shell, I can use `pixi shell-hook` which augments `PATH` and sets some env variables.

Wouldn't it be possible to do this in a "GitHub Actions-native" way? I.e.

```
echo "<env_path>" >> $GITHUB_PATH
echo "CONDA_PREFIX=..." >> $GITHUB_ENV
echo "PIXI_PROMPT=..." >> $GITHUB_ENV
...
```

This would allow all subsequent steps (including those using external actions that potentially call binaries in the path via `actions/exec`) to access binaries in `.pixi/envs/.../bin`.

Is there any downside to supporting this behind a flag? Is there a benefit that I'm missing to always require `pixi run`?

This feature would also come in handy if not using the default environment (which requires to always specify `-e <env>` for `pixi run`) and/or when a task runner other than `pixi` is used which should work without needing to know about the installation process of binaries (i.e. that it should use `pixi run XXX` rather than `XXX`).

**Comment by wolfv** [comment]
Some conda packages require "activation" and environment variables (beyond PATH) to be set. 

But what we could do is: execute the activation once, and record any new env vars. We could then export them to $GITHUB_ENV. And similarly add the PATH changes. 

We could even integrate that into pixi. However this would only work for one environnment ... (eg the default) and might give trouble if more are used.

**Comment by borchero** [comment]
> Some conda packages require "activation" and environment variables (beyond PATH) to be set.

Good point, I forgot about the activation scripts :eyes:

> But what we could do is: execute the activation once, and record any new env vars. We could then export them to $GITHUB_ENV. And similarly add the PATH changes.

In theory, that sounds very reasonable :smile: as far as I can tell, nothing prevents activation scripts from doing more than setting env vars, right? In this case, activation might be "incomplete"? 🤔 nonetheless, I think that this would be a working solution for the overwhelming majority of packages and I would be very much in favor of doing this (guarded by a flag and a caveat in the documentation).

> We could even integrate that into pixi.

I'm not sure I understand why this would be necessary... isn't `eval $(pixi shell-hook)` doing exactly that?

**Comment by borchero** [comment]
I've tried this out in my own fork and it works quite nicely, see https://github.com/prefix-dev/setup-pixi/compare/main...borchero:activate (I haven't opened a PR yet since I wasn't sure whether this direction is desirable -- for the same reason, I haven't written any tests yet and only tried in out in a private repo of mine).

**Comment by wolfv** [comment]
Nice! We could also add a function to pixi to emit the shell hook / activation env vars as JSON :)

I believe we have two modes for activation - in one we run the activation scripts and record the diff (that's what pixi uses for `run` and other commands), and the shell-hook which only prints the actual "script").

So we could use the first option and turn it into a JSON or something like that.

**Comment by borchero** [comment]
> We could also add a function to pixi to emit the shell hook / activation env vars as JSON

That would make the implementation here very convenient, of course :smile: I can imagine this to be a useful feature in other contexts as well (e.g. other CI systems, potentially also Dockerfiles)

> in one we run the activation scripts and record the diff

I didn't know that this already exists in `pixi`, neat ;)

> So we could use the first option and turn it into a JSON or something like that.

Sounds good to me, the most useful format for GitHub Actions would be something like:

```json
{
    "pathComponents": ["<path>"],
    "environmentVariables": {
         "<key>": "<value>"
    }
}
```

Shall we move the discussion on the API to https://github.com/prefix-dev/pixi?
