### ISSUE TITLE
allow to specify working directory

### ISSUE THREAD

**Issue by lev112** [prefix-dev/setup-pixi#133]
in the existing implementation, while installing pixi, 
the action expects to find `pixi.toml` and `pixi.lock` in the root directory of the repo.

it is possible to have a pixi project in a sub folder (for example in a mono repo with multiple projects),
and at the moment it's not possible to use the action in that case.

in my case I'm getting the error
> Error: Failed to generate cache key: Error: ENOENT: no such file or directory, open 'pixi.lock'

since the lock file is in a sub folder

**Comment by pavelzw** [comment]
Doesn't specifying `manifest-path` work in this case?

**Comment by lev112** [comment]
thanks @pavelzw, you are correct.
for some reason, when reading the docs I thought that option is only used to pick the name of the file and not the project root as a whole.
