### ISSUE TITLE
Editable package not reinstalled after cache hit, so `_version.py` missing

### ISSUE THREAD

**Issue by maresb** [prefix-dev/setup-pixi#136]
I like using [setuptools_scm](https://github.com/pypa/setuptools_scm) to manage the versioning of my Python projects via Git tags. It can be configured so that whenever a package is built or installed, `setuptools_scm` will generate a `_version.py` file in the source tree containing the version metadata. (The `_version.py` is added to `.gitignore` so that it can be updated dynamically.)

Now for the problem: I configure my default pixi feature with an editable install of my project. If the cache is enabled, and if there's a cache hit, then my `_version.py` file is missing. That's apparently because the `_version.py` file is neither in pixi's cache (since it's an editable install) nor is it in the source tree (because it's in the `.gitignore` and expected to be generated dynamically on reinstall). And finally, due to the cache hit, it seems that pixi doesn't trigger a reinstall.

I'm not sure that this is an actual bug since under most circumstances it's not necessary to reinstall an editable-installed Python project after loading it from the cache. But I wanted to at least raise visibility of this edge case.

This might be fixable by something like https://github.com/prefix-dev/pixi/discussions/1897

**Comment by pavelzw** [comment]
How about not generating a `_version.py` dynamically? This seems like it can cause lots of weird unpredictable issues.
I personally always just add the following to my `my_project/__init__.py`

```py
import importlib.metadata
import warnings

try:
    __version__ = importlib.metadata.version(__name__)
except importlib.metadata.PackageNotFoundError as e:
    warnings.warn(f"Could not determine version of {__name__}\n{e!s}", stacklevel=2)
    __version__ = "unknown"
```

Dynamically generating python files just for the version seems like a weird hack to me that should be fixed in a different way...

**Comment by pavelzw** [comment]
ah i saw that you actually do this in https://github.com/maresb/pymc-gpx/pull/4

**Comment by maresb** [comment]
Ya, agreed that it's pretty hacky. However one disadvantage to `importlib.metadata.version` is performance. Parsing the `METADATA` can be really slow, like I think it was a few hundred ms, at least as of a few years ago. Not ideal for something that runs each time you import a project.

These days my attitude is more that if you care at all about performance then Python is probably the wrong language. :joy: So I think there aren't many cases where this is worthwhile.

Probably there's nothing to implement here, so feel free to close this. Thanks so much for taking the time to respond!
