### ISSUE TITLE
Mac OS runner no longer adds pixi to path

### ISSUE THREAD

**Issue by hoxbro** [prefix-dev/setup-pixi#139]
We are starting to see things fail around Friday (see [here](https://github.com/holoviz/spatialpandas/actions/runs/10867331730/job/30155969184)). Our Mac OS CI is beginning to fail because Pixi is no longer added to the path. 

This is likely related to a new runner image from Github, version number `20240911.3`, as `20240903.5` seems to work fine. 

The temporary solution right now is manually adding it to the path. But it is not ideal, and it makes ` shell: pixi run -e {env} bash -e {0}` hard to do. (Edit: Seems to only be with `... -el {0}`.)

Also, I'm unsure if this is a problem with how we have set things up in our CI, with how `setup-pixi` works, or a Github problem.

**Comment by pavelzw** [comment]
hmm i just reran the CI in this repo on the latest commit on macos-latest and couldn't see your issues, see https://github.com/prefix-dev/setup-pixi/actions/runs/10777185748/job/30167268763

do you have a more simple failing reproducible example?

**Comment by hoxbro** [comment]
Created this repo: https://github.com/hoxbro/example-repo/actions/runs/10878803249, with a MRE.

It seems to be caused when you have `shell: bash -el {0}` enabled.

**Comment by pavelzw** [comment]
hmm this is a bit odd... can you run the following as well in both the `-e` and `-el` steps?

```
echo $PATH
```

also, can you show me the contents of `~/.bash_profile` on the runners? (i.e. run `cat ~/.bash_profile`) this is what gets sourced when specifying `-l`

**Comment by pavelzw** [comment]
probably you still had `-l` from https://github.com/mamba-org/setup-micromamba. this is not required with setup-pixi anymore as it was a hack to get `micromamba activate` working before.

**Comment by hoxbro** [comment]
See https://github.com/hoxbro/example-repo/actions/runs/10879060685/job/30183040885

> probably you still had -l from ... this is not required with setup-pixi

You are correct. But I still think `setup-pixi` should work with `bash -el` on Mac OS. I don't think it is that uncommon when coming from `setup-miniconda` / `setup-micromamba`.

**Comment by pavelzw** [comment]
it looks like this part of the `bash_profile` is overriding the path that's set...

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/28178488-26fe-4e0f-883f-3ec2f0fbf60f">

no idea why they changed it to this, this breaks all `echo ... >> $GITHUB_PATH` usages when using `-l`.

this is unfortunately not something we can change in this repo, we would need to get this fixed upstream in https://github.com/actions/runner-images/issues.
would you like to create an issue?

**Comment by hoxbro** [comment]
Done here: https://github.com/actions/runner-images/issues/10624

**Comment by mattwthompson** [comment]
Based on the last linked PR there, it looks like the login shell isn't needed (for at least that case)

**Comment by pavelzw** [comment]
the login shell is only needed in setup-micromamba. for setup-pixi it's completely irrelevant and imo you should delete that part anyway

**Comment by pavelzw** [comment]
Seems to be fixed upstream. @hoxbro is the issue gone on your end?
