### ISSUE TITLE
is authentification when using GH actions always required?

### ISSUE THREAD

**Issue by jgunstone** [prefix-dev/setup-pixi#141]
hi there - 
getting started with pixi and so far so awesome - 

looking to add testing via GH actions, in the past when I used micromamba for this it has required authentification... 
is this always required, even if all my packages are publicly available on pypi / conda-forge? if yes, how come?

many thanks

**Comment by wolfv** [comment]
Hey @jgunstone , if all your dependencies are on eg conda-forge and pypi then authentication should not be needed :)
