### ISSUE TITLE
The process '/home/runner/.pixi/bin/pixi' failed with exit code 1

### ISSUE THREAD

**Issue by jgunstone** [prefix-dev/setup-pixi#142]
I'm trying to setup simple CI with pixi on a repo and am struggling - I'm sure it is an issue with my config but was hoping you might be able to spot the problem... 

[`pyproject.yml`](https://github.com/maxfordham/xlsxdatagrid/blob/configure-pixi/pyproject.toml)
[`ci.yml`](https://github.com/maxfordham/xlsxdatagrid/blob/configure-pixi/.github/workflows/ci.yml)

https://github.com/maxfordham/xlsxdatagrid/actions/runs/11093819769/job/30820568152

followed docs here:
- https://pixi.sh/latest/advanced/github_actions/#usage
- https://pixi.sh/latest/advanced/github_actions/#using-the-pyprojecttoml-as-a-manifest-file-for-pixi

error: 

```console
[linux-64](https://github.com/maxfordham/xlsxdatagrid/actions/runs/11093892943/job/30820726970#logs)
failed 7 minutes ago in 3s
Search logs
[1](https://github.com/maxfordham/xlsxdatagrid/actions/runs/11093892943/job/30820726970#step:1:1)s
Current runner version: '2.319.1'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'prefix-dev/setup-pixi@v0.8.0' (SHA:[2](https://github.com/maxfordham/xlsxdatagrid/actions/runs/11093892943/job/30820726970#step:1:2)058dcd92f5dbe3befd7379ec[6](https://github.com/maxfordham/xlsxdatagrid/actions/runs/11093892943/job/30820726970#step:1:7)a3022bb746bdfd)
Complete job name: linux-64
0s
Run prefix-dev/setup-pixi@v0.8.0
Downloading Pixi
pixi install
Error: The process '/home/runner/.pixi/bin/pixi' failed with exit code 1
```

many thanks

(fyi these guys seem to be having the same issue: https://github.com/Quantco/polarify/actions/runs/8480496003)

**Comment by pavelzw** [comment]
You are missing a `uses: actions/checkout@v4`

**Comment by jgunstone** [comment]
knew it would be something simple - now working beautifully! 
thanks so much for your help

BTW - I'm loving how much pixi simplifies setting up CI
