### ISSUE TITLE
Add `pixi list` at the end of the action

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/setup-pixi#4]
depends on https://github.com/prefix-dev/pixi/issues/238

**Comment by ruben-arts** [comment]
This indeed has to wait for the command in pixi. Meanwhile you could print the `pixi.lock` or export it as an artifact to at least have the information available while debugging.

**Comment by pavelzw** [comment]
Ideally we would want to use `--frozen-lockfile` like in npm/pnpm.
