### ISSUE TITLE
Support installer environment variables?

### ISSUE THREAD

**Issue by wpbonelli** [prefix-dev/setup-pixi#97]
The pixi docs describe several environment variables which control the behavior of the installer scripts. I know this action installs pixi via [`downloadTool()`](https://github.com/actions/toolkit/tree/main/packages/tool-cache#download), not with the install scripts, but perhaps still worth supporting? At least the ones shared on all platforms:

- `PIXI_VERSION` (this is just `VERSION` on linux/mac, maybe worth standardizing?)
- `PIXI_HOME`

Just convenience, but it would be nice to be able to set `PIXI_VERSION` at the top of a workflow instead of setting `version` separately wherever this action is used.

I guess the way to do this would be to check `process.env` [here](https://github.com/prefix-dev/setup-pixi/blob/4fc8d82a01877bbbcb485e8282bd48539d8adc84/src/options.ts#L161)

**Comment by pavelzw** [comment]
I want to keep `downloadTool` as changing this to for example the install.sh script can break things in corporate environments behind a proxy (I had this problem in https://github.com/mamba-org/setup-micromamba/pull/61 before).

Not sure about `PIXI_VERSION` as this introduces a second way to basically do the same thing without being clear which the preferred way is. I'm also unsure how other `setup-*` actions do this. I would suppose they also only use the GitHub-provided input arguments.

**Comment by wpbonelli** [comment]
It does look like other `setup-*` actions just use the input. I will close this.
